apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pepe-project.fullname" . }}
  labels:
    {{- include "pepe-project.labels" . | nindent 4 }}  
data:
  {{- toYaml .Values.configmap | nindent 2 }}

