apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pepe-project.fullname" . }}
  labels:
    {{- include "pepe-project.labels" . | nindent 4 }}  
data:
  {{- toYaml .Values.secret | nindent 2 }}
